if ~exist(expdir,'dir'),
  error('Experiment directory %s does not exist',expdir);
end

[analysis_protocol,settingsdir,datalocparamsfilestr,leftovers] = ...
  myparse_nocheck(varargin,...
  'analysis_protocol','current',...
  'settingsdir','/groups/branson/bransonlab/projects/CourtshipBowls/CourtshipBowlAnalysis/settings',...
  'datalocparamsfilestr','dataloc_params.txt');

datalocparamsfile = fullfile(settingsdir,analysis_protocol,datalocparamsfilestr);
dataloc_params = ReadParams(datalocparamsfile);
